name: mobile_health_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0 # Firestore authentication
  cloud_firestore: ^2.3.0 # Firestore cloud storage

  # Fonts + visuals
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  bordered_text: ^2.0.0 # package to add a border to text (i.e. black text with a white border
  font_awesome_flutter: ^9.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_spinkit: ^5.0.0

  # OCR/Camera packages
  google_ml_kit: ^0.6.0 # google's ML kit - used for the text recognition
  camera: ^0.8.1+3 # camera package to be able to access the device's camera
  path_provider: ^2.0.2 # path provider package to find local files/photos
  image_picker: ^0.8.3 # package to prompt the user to pick an image from their phone's gallery

  # Analysis packages
  calc: ^0.2.1 # used for health analysis (variance, standard deviation)
  fl_chart: ^0.36.3

  # Notification packages
  flutter_local_notifications: ^8.0.0
  firebase_messaging: ^10.0.4

  # Miscellaneous
  wc_form_validators: ^1.0.0
  fluttertoast: ^8.0.7 # used for 'wrong email/password' notices in the deletion alerts


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/

